title: StartOps Digital
email: fabian@startops.digital
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: https://startops.digital
twitter_username: jekyllrb
github_username:  jekyll
plugins: []

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

name: StartOps.digital
baseurl: ""
url: https://startops.digital
github: chainsquad
markdown: kramdown
excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: compressed
